import { ArrowDownRight, ArrowUpRight, CalendarDays, ChevronRight, RefreshCw, TrendingDown } from 'lucide-react';
import { Link } from 'wouter';
import { useGetCloudSpendDashboard, getGetCloudSpendDashboardQueryKey } from '@workspace/api-client-react';
import { AppShell, getUsername, PageHeader, StatSkeleton } from '@/components/app-shell';
import { SmartBudgetAlert } from '@/components/smart-budget-alert';

const money = (value = 0) => `$${value.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const dateLabel = (value: string) => new Date(`${value}T12:00:00`).toLocaleDateString(undefined, { month: 'short', day: 'numeric' });
const colors = ['#2f8272', '#d8a34e', '#6da6bd', '#d47b6e', '#9d8aba', '#5b7280'];

function DashboardSkeleton() {
  return <AppShell><PageHeader eyebrow="Your overview" title="Loading your month…" description="Pulling the useful bits together." /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><StatSkeleton /><StatSkeleton /><StatSkeleton /><StatSkeleton /></div><div className="mt-5 grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><div className="skeleton h-80 rounded-2xl" /><div className="skeleton h-80 rounded-2xl" /></div></AppShell>;
}

export default function Dashboard() {
  const username = getUsername();
  const { data, isLoading, isError, refetch } = useGetCloudSpendDashboard(username, { query: { queryKey: getGetCloudSpendDashboardQueryKey(username) } });
  if (isLoading) return <DashboardSkeleton />;
  if (isError || !data) return <AppShell><div className="page-enter flex min-h-[60vh] items-center justify-center"><div className="max-w-sm text-center"><div className="mx-auto mb-5 grid h-14 w-14 place-items-center rounded-2xl bg-destructive/10 text-destructive"><RefreshCw className="h-6 w-6" /></div><h1 className="text-2xl font-extrabold tracking-tight">That view got away.</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">We couldn’t load your spending right now. Your data is safe — try again in a moment.</p><button type="button" data-testid="button-retry-dashboard" onClick={() => refetch()} className="mt-6 rounded-xl bg-primary px-5 py-3 text-sm font-bold text-primary-foreground">Try again</button></div></div></AppShell>;
  const { summary, categoryBreakdown, trend, recentExpenses, user } = data;
  const budgetUsed = user.monthlyBudget ? Math.min(100, Math.round((summary.monthSpend / user.monthlyBudget) * 100)) : 0;
  const comparisonPositive = data.monthComparison > 0;
  const maxTrend = Math.max(...trend.map((item) => item.amount), 1);
  let categoryStart = 0;
  const categoryGradient = categoryBreakdown.map((item, i) => {
    const end = categoryStart + (summary.monthSpend ? (item.amount / summary.monthSpend) * 360 : 0);
    const segment = `${colors[i % colors.length]} ${categoryStart}deg ${end}deg`;
    categoryStart = end;
    return segment;
  }).join(', ');
  return <AppShell><PageHeader eyebrow="Your overview" title={`Good to see you, ${username}.`} description="A clear read on where your money has been, and where it can go next." action={<Link href="/expenses" data-testid="link-add-from-dashboard" className="rounded-xl bg-primary px-4 py-3 text-sm font-bold text-primary-foreground shadow-sm transition-transform hover:-translate-y-0.5">Add an expense</Link>} />
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
      <div className="page-enter stagger-1 rounded-2xl border border-border bg-card p-5"><p className="text-xs font-bold text-muted-foreground">This month</p><p className="mt-4 font-mono text-3xl font-medium tracking-[-0.05em]" data-testid="text-month-spend">{money(summary.monthSpend)}</p><div className={`mt-3 flex items-center gap-1 text-xs font-bold ${comparisonPositive ? 'text-destructive' : 'text-primary'}`}>{comparisonPositive ? <ArrowUpRight className="h-3.5 w-3.5" /> : <ArrowDownRight className="h-3.5 w-3.5" />}{Math.abs(data.monthComparison).toFixed(1)}% vs last month</div></div>
      <div className="page-enter stagger-2 rounded-2xl border border-border bg-card p-5"><p className="text-xs font-bold text-muted-foreground">All-time total</p><p className="mt-4 font-mono text-3xl font-medium tracking-[-0.05em]" data-testid="text-total-spend">{money(summary.total)}</p><p className="mt-3 text-xs text-muted-foreground">{summary.count} recorded {summary.count === 1 ? 'expense' : 'expenses'}</p></div>
      <div className="page-enter stagger-3 rounded-2xl border border-border bg-card p-5"><p className="text-xs font-bold text-muted-foreground">Average expense</p><p className="mt-4 font-mono text-3xl font-medium tracking-[-0.05em]" data-testid="text-average-spend">{money(summary.average)}</p><p className="mt-3 text-xs text-muted-foreground">Largest: {money(summary.highest)}</p></div>
      <div className="page-enter stagger-4 rounded-2xl border border-primary/20 bg-[#e2f2ec] p-5"><div className="flex items-center justify-between"><p className="text-xs font-bold text-[#286658]">Budget health</p><span className="rounded-full bg-[#c2e4d6] px-2 py-1 text-[10px] font-extrabold text-[#286658]">{budgetUsed}% used</span></div><p className="mt-4 font-mono text-3xl font-medium tracking-[-0.05em] text-[#1f554b]" data-testid="text-budget-remaining">{money(Math.max(user.monthlyBudget - summary.monthSpend, 0))}</p><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-[#bedccd]"><div className="h-full rounded-full bg-primary transition-all duration-700" style={{ width: `${budgetUsed}%` }} /></div></div>
    </div>
     <div className="page-enter mt-5"><SmartBudgetAlert monthlyBudget={user.monthlyBudget} monthSpend={summary.monthSpend} categoryBudgets={user.categoryBudgets} categoryBreakdown={categoryBreakdown} compact /></div>
    <div className="mt-5 grid gap-5 lg:grid-cols-[1.35fr_.65fr]">
      <section className="page-enter rounded-2xl border border-border bg-card p-5 sm:p-6"><div className="flex items-start justify-between"><div><h2 className="font-extrabold tracking-tight">Spending rhythm</h2><p className="mt-1 text-xs text-muted-foreground">Daily activity in the last 30 days</p></div><span className="grid h-9 w-9 place-items-center rounded-xl bg-secondary text-secondary-foreground"><TrendingDown className="h-4 w-4" /></span></div><div className="mt-8 flex h-44 items-end gap-1.5 sm:gap-2">{trend.length ? trend.map((point, index) => <div key={`${point.date}-${index}`} className="group flex h-full flex-1 flex-col justify-end"><div className="relative w-full rounded-t-md bg-primary/75 transition-all duration-300 group-hover:bg-primary" style={{ height: `${Math.max(5, (point.amount / maxTrend) * 100)}%` }} title={`${dateLabel(point.date)} ${money(point.amount)}`} /><span className="mt-2 text-center text-[9px] text-muted-foreground">{index % Math.max(1, Math.ceil(trend.length / 6)) === 0 ? dateLabel(point.date) : ''}</span></div>) : <div className="flex w-full items-center justify-center text-sm text-muted-foreground">Your rhythm will appear here.</div>}</div></section>
      <section className="page-enter rounded-2xl border border-border bg-card p-5 sm:p-6"><div className="flex items-start justify-between"><div><h2 className="font-extrabold tracking-tight">Category mix</h2><p className="mt-1 text-xs text-muted-foreground">Where this month went</p></div><CalendarDays className="h-4 w-4 text-muted-foreground" /></div><div className="mt-7 flex items-center gap-5">{categoryBreakdown.length ? <><div className="relative h-32 w-32 shrink-0 rounded-full" style={{ background: `conic-gradient(${categoryGradient})` }}><div className="absolute inset-5 grid place-items-center rounded-full bg-card text-center"><span className="font-mono text-lg font-medium">{money(summary.monthSpend)}</span></div></div><div className="min-w-0 flex-1 space-y-2.5">{categoryBreakdown.slice(0, 5).map((item, i) => <div key={item.category} className="flex items-center justify-between gap-2 text-xs"><span className="flex min-w-0 items-center gap-2 truncate"><i className="h-2 w-2 shrink-0 rounded-full" style={{ background: colors[i % colors.length] }} />{item.category}</span><span className="font-mono text-muted-foreground">{money(item.amount)}</span></div>)}</div></> : <p className="py-10 text-sm text-muted-foreground">No categories yet. Add your first expense to see the mix.</p>}</div></section>
    </div>
    <section className="page-enter mt-5 rounded-2xl border border-border bg-card"><div className="flex items-center justify-between border-b border-border px-5 py-5 sm:px-6"><div><h2 className="font-extrabold tracking-tight">Recent activity</h2><p className="mt-1 text-xs text-muted-foreground">Your latest money moments</p></div><Link href="/expenses" data-testid="link-view-all-expenses" className="flex items-center gap-1 text-xs font-bold text-primary hover:underline">View all <ChevronRight className="h-3.5 w-3.5" /></Link></div>{recentExpenses.length ? <div className="divide-y divide-border">{recentExpenses.slice(0, 5).map((expense) => <div key={expense.id} data-testid={`row-recent-expense-${expense.id}`} className="flex items-center justify-between gap-4 px-5 py-4 sm:px-6"><div className="flex min-w-0 items-center gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-secondary text-xs font-extrabold text-secondary-foreground">{expense.category.slice(0, 1)}</span><div className="min-w-0"><p className="truncate text-sm font-bold">{expense.description}</p><p className="mt-0.5 text-xs text-muted-foreground">{expense.category} · {dateLabel(expense.date)}</p></div></div><span className="shrink-0 font-mono text-sm font-medium">{money(expense.amount)}</span></div>)}</div> : <div className="p-10 text-center"><p className="font-bold">Nothing here yet.</p><p className="mt-1 text-sm text-muted-foreground">Your first expense will make this space useful.</p></div>}</section>
  </AppShell>;
}